apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
spec:
  selector:
    matchLabels:
      app: weatherapp
  replicas: 2
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - name: weatherapp
        image: 872444258103.dkr.ecr.us-east-1.amazonaws.com/weatherapp:${TAG}
        ports:
        - containerPort: 5000
        env:
        - name: TAG 
          value: "cf3c1bc188817ccabff747048e32cf7ca3efc2f8-28"

---
apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  labels:
    app: weatherapp
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: 5000
  selector:
    app: weatherapp
